export SAMPLER_SPARSITY=1
export SAMPLER_EVENT_COUNTDOWNS=1
export SAMPLER_FILE=report
export SAMPLER_EXIT_SIGNAL=0
export SAMPLER_EXIT_STATUS=0
export CBI_HOME=`pwd`
export PATH="$CBI_HOME/bin/:$PATH"
export LD_LIBRARY_PATH="$CBI_HOME/sampler-1.6.2/driver/lib/:$LD_LIBRARY_PATH"
