#!/bin/sh

PACKAGE='sampler'

prefix='/usr/local'
exec_prefix="${prefix}"
libdir="${exec_prefix}/lib"
pkglibdir="${libdir}/${PACKAGE}"
driverdir="${pkglibdir}/driver"
echo "/usr/bin/gcc -B $driverdir -specs=sampler-specs $@"
exec '/usr/bin/gcc' -B "$driverdir" -specs=sampler-specs "$@"
