#!/bin/sh

driverdir=`dirname $0`
homedir=$driverdir/..

exec '/usr/bin/gcc' -B "$driverdir" -specs=sampler-specs -fsampler-random=online "$@"
#exec '/usr/bin/gcc' -B "$driverdir" -specs=sampler-specs --sampler-lib-dir="$driverdir/lib" "$@"
